name: Deploy to AWS EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Navigate to app directory
          cd /home/ubuntu/impuesto_bot
          
          # Pull latest code
          git pull origin main
          
          # Stop existing containers
          docker-compose down --remove-orphans
          
          # Build and start new containers
          docker-compose up -d --build app
          
          # Clean up old images
          docker image prune -f
          
          # Show running containers
          docker-compose ps
          
          # Health check - wait for app to start
          sleep 15
          curl -f http://localhost:8000/health || exit 1
          
          echo "🚀 Deployment completed successfully!"
